version: "3.8"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c "npm run build && node dist/src/index.js"

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=usr_pg
      - POSTGRES_PASSWORD=pw_pg
      - POSTGRES_DB=mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ../scripts/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
