version: "3.8"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
    command: sh -c "npm run build && node dist/src/index.js"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ../scripts/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql

volumes:
  db-data:
